In [ ]:
import numpy as np

In [ ]:
students = {
    "ID" : [1,2,3,4,5],
    "Gender" : ["Male","Female","Male","Female","Male"],
    "Department" : ["CSE", "ECE" ,"CSE" , "CSE", "ECE"]
}

In [ ]:
gender_male = np.array([1,0,1,0,1] , dtype = np.uint8)
gender_female = np.array([0,1,0,1,0] , dtype = np.uint8)

dept_cse = np.array([1,0,0,1,0] , dtype = np.uint8)
dept_ece = np.array([0,1,0,0,1] , dtype = np.uint8)
dept_it = np.array([0,0,1,0,0] , dtype = np.uint8)

In [ ]:
packed_male = np.packbits(gender_male)
packed_cse = np.packbits(dept_cse)

print(packed_male)
print(packed_cse)

[168]
[144]


In [ ]:
print(np.unpackbits(packed_male)[:5])
print(np.unpackbits(packed_cse)[:5])

[1 0 1 0 1]
[1 0 0 1 0]


In [ ]:
result = np.bitwise_and(gender_male, dept_cse)
print(result)

[1 0 0 0 0]


In [ ]:
ids = np.array(students["ID"])
print(ids[result == 1])

[1]


In [ ]:
result = np.bitwise_or(dept_it, dept_cse)
print(ids[result == 1])

[1 3 4]


In [ ]:
result = np.logical_not(gender_male).astype(np.uint8)
print(ids[result == 1])

[2 4]


In [ ]:
class BitmapIndexEngine:

    def __init__(self, ids):
        self.ids = np.array(ids)

    def query_and(self, bitmap1, bitmap2):
        result = np.bitwise_and(bitmap1, bitmap2)
        return self.ids[result == 1]

    def query_or(self, bitmap1, bitmap2):
        result = np.bitwise_or(bitmap1, bitmap2)
        return self.ids[result == 1]

    def query_not(self, bitmap):
      result = np.logical_not(bitmap).astype(np.uint8)
      return self.ids[result == 1]

In [ ]:
engine = BitmapIndexEngine(students["ID"])
oo
print("Male AND CSE")
print(engine.query_and(gender_male, dept_cse))

print()

print("CSE OR IT")
print(engine.query_or(dept_cse, dept_it))

print()

print("NOT Male")
print(engine.query_not(gender_male))

Male AND CSE
[1]

CSE OR IT
[1 3 4]

NOT Male
[2 4]
